/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasDesign: typeof import('./src/components/CanvasDesign.vue')['default']
    ComponentLibrary: typeof import('./src/components/ComponentLibrary.vue')['default']
    DialogImport: typeof import('./src/components/DialogImport.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    HeaderButton: typeof import('./src/components/HeaderButton.vue')['default']
    InputImport: typeof import('./src/components/InputImport.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const CanvasDesign: typeof import('./src/components/CanvasDesign.vue')['default']
  const ComponentLibrary: typeof import('./src/components/ComponentLibrary.vue')['default']
  const DialogImport: typeof import('./src/components/DialogImport.vue')['default']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const HeaderButton: typeof import('./src/components/HeaderButton.vue')['default']
  const InputImport: typeof import('./src/components/InputImport.vue')['default']
  const PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}